niwas/hostupload/urls.py
from django.urls import path
from hostupload import views

app_name = 'hostupload'

urlpatterns = [
    path('host/',views.UploadFormview,name='host'),
    path('hostel/',views.UploadHostelview,name='hostel'),
    path('house/',views.UploadHouseview,name='house'),

]

niwas/niwas/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path,include,re_path

from account.views import user_login,index
from client.views import  home
from niwas import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='index'),
    path('login/', user_login, name='login'),
    path('hosting/' , include('hostupload.urls')),
    path('account/', include("account.urls")),
    re_path(r'^accounts/', include('account.passwords.urls')),
    path('client_page1/' , include('client_page1.urls')),
    path('client_pages2/',include('client_pages2.urls')),
    path('client/',include('client.urls')),

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

niwas/hostupload/models.py
from django.db import models


# Create your models here.
from django.contrib.auth.models import User


TYPE_CHOICES=(
    ('1', 'Hostel'),
    ('2','House'),
    ('3','Appartment')
    )


class Amenities(models.Model):
    am_id = models.AutoField(primary_key=True)
    amenities = models.CharField(max_length=100)
    pictures = models.ImageField(upload_to='photos', blank=True)
    def __str__(self):
        return self.amenities


class Address(models.Model):
    street = models.CharField(max_length=250)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    zipcode = models.IntegerField()


class Property_Upload(models.Model):
    pr_type = models.CharField(choices=TYPE_CHOICES,max_length=10)
    address = models.OneToOneField(Address, on_delete=models.CASCADE)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    shareable = models.BooleanField()
    pr_is_personal = models.BooleanField()
    for_business = models.BooleanField()

class Gallery(models.Model):
    pr = models.ForeignKey(Property_Upload ,on_delete=models.CASCADE)
    img = models.ImageField(upload_to='photos',blank=True)

class Pricing_House(models.Model):
    pr = models.OneToOneField(Property_Upload , on_delete=models.CASCADE)
    single_a = models.IntegerField()
    single_wa = models.IntegerField()
    double_a = models.IntegerField()
    double_wa = models.IntegerField()
    triple_a = models.IntegerField()
    triple_wa = models.IntegerField()
    floorbed = models.IntegerField()
    cleaning = models.IntegerField()
    security = models.IntegerField()
    extra = models.IntegerField()

class House(models.Model):
    pr = models.OneToOneField(Property_Upload , on_delete=models.CASCADE)
    single_a = models.IntegerField()
    single_wa = models.IntegerField()
    double_a = models.IntegerField()
    double_wa = models.IntegerField()
    triple_a = models.IntegerField()
    triple_wa = models.IntegerField()
    floorbed = models.IntegerField()
    amenities = models.ManyToManyField(Amenities)
    price = models.OneToOneField(Pricing_House , on_delete=models.CASCADE)
    avg_rating = models.IntegerField(default=1)
    description = models.TextField(null=True)
    guest = models.IntegerField(null=True)

class Pricing_Hostel(models.Model):
    pr = models.OneToOneField(Property_Upload , on_delete=models.CASCADE)
    single_a = models.IntegerField()
    single_wa = models.IntegerField()
    double_a = models.IntegerField()
    double_wa = models.IntegerField()
    triple_a = models.IntegerField()
    triple_wa = models.IntegerField()
    four_a = models.IntegerField()
    four_wa = models.IntegerField()
    cleaning = models.IntegerField()
    security = models.IntegerField()
    cab = models.IntegerField()
    food = models.IntegerField()
    extra = models.IntegerField()



class Hostel(models.Model):
    pr = models.OneToOneField(Property_Upload , on_delete=models.CASCADE)
    single_a = models.IntegerField()
    single_wa = models.IntegerField()
    double_a = models.IntegerField()
    double_wa = models.IntegerField()
    triple_a = models.IntegerField()
    triple_wa = models.IntegerField()
    four_a = models.IntegerField()
    four_wa = models.IntegerField()
    amenities = models.ManyToManyField(Amenities)
    price = models.OneToOneField(Pricing_Hostel , on_delete=models.CASCADE)
    avg_rating = models.IntegerField(default=1)
    description = models.TextField(null=True)
    gallery = models.URLField(null=True)



class Booking_House(models.Model):
    pr = models.ForeignKey(Property_Upload,on_delete=models.CASCADE)
    user = models.ForeignKey(User , on_delete=models.CASCADE)
    check_in = models.DateField()
    check_out = models.DateField()
    single_a = models.IntegerField(null=True)
    single_wa = models.IntegerField(null=True)
    double_a = models.IntegerField(null=True)
    double_wa = models.IntegerField(null=True)
    triple_a = models.IntegerField(null=True)
    triple_wa = models.IntegerField(null=True)
    floorbed = models.IntegerField(default=0)
    price_paid = models.IntegerField()
    Rating = models.IntegerField(null=True)
    status = models.IntegerField(default=1)
    Feedback = models.TextField(null=True)



class Booking_Hostel(models.Model):
    pr = models.ForeignKey(Property_Upload,on_delete=models.CASCADE)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    check_in = models.DateField()
    check_out = models.DateField()
    single_a = models.IntegerField(null=True)
    single_wa = models.IntegerField(null=True)
    double_a = models.IntegerField(null=True)
    double_wa = models.IntegerField(null=True)
    triple_a = models.IntegerField(null=True)
    triple_wa = models.IntegerField(null=True)
    four_a = models.IntegerField(null=True)
    four_wa = models.IntegerField(null=True)
    price_paid = models.IntegerField()
    Rating = models.IntegerField(null=True)
    status = models.IntegerField(default=1)
    Feedback = models.TextField(null=True)


class feedback(models.Model):
    pr = models.ForeignKey(Property_Upload,on_delete=models.CASCADE)
    feedback = models.TextField()
    rating = models.IntegerField()

niwas/hostupload/forms.py
from hostupload.models import *
from django.forms import ModelForm
from django.contrib.auth.models import User
from django import forms
from django.db import models





class AddressForm(ModelForm):
    class Meta:
        model = Address
        fields = '__all__'

class Pricing_HostelForm(ModelForm):
    class Meta:
        model = Pricing_Hostel
        fields = ['single_a','single_wa','double_a','double_wa','triple_a','triple_wa','four_a','four_wa','cleaning','security','cab','food','extra']


class Pricing_HouseForm(ModelForm):
    class Meta:
        model = Pricing_House
        fields = ['single_a','single_wa','double_a','double_wa','triple_a','triple_wa','floorbed','cleaning','security','extra']


# class AmenitiesForm(ModelForm):
#     # AMEN_CHOICES=(
#     # ('1','A.C'),
#     # ('2','Freeze'),
#     # ('3','Cooler'),
#     # )
#     #
#     # model_categories = forms.MultipleChoiceField(
#     #             widget = forms.CheckboxSelectMultiple,
#     #             choices = AMEN_CHOICES
#     #     )
#     # class Meta:
#     #     model = Amenities
#     #     fields = ['model_categories']
#      amenities = forms.ModelMultipleChoiceField(queryset=Amenities.objects.all(),
#      widget=forms.CheckboxSelectMultiple)
#      class Meta:
#         model=Amenities
#         fields=["amenities"]

class UploadForm(ModelForm):
    class Meta:
        model = Property_Upload
        fields = ['shareable','pr_is_personal','for_business','pr_type']

class HostelForm(ModelForm):
    class Meta:
        model = Hostel
        fields = ['single_a','single_wa','double_a','double_wa','triple_a','triple_wa','four_a','four_wa','amenities','description']



class HouseForm(ModelForm):
    class Meta:
        model = House
        fields = ['single_a','single_wa','double_a','double_wa','triple_a','triple_wa','floorbed','amenities','description']

niwas/hostupload/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render,redirect,reverse
from hostupload.forms import AddressForm,Pricing_HostelForm,Pricing_HouseForm,UploadForm,HostelForm,HouseForm
# Create your views here.
from django.http import HttpResponse,HttpResponseRedirect
from hostupload.models import Property_Upload,Hostel,Amenities,Gallery
from django.contrib.auth.models import User
from django.forms.models import modelformset_factory

def UploadHostelview(request):
    ImageFormset = modelformset_factory(Gallery, fields=('img',), extra=3 , max_num=8)


    if request.method=='POST':
        hostel = HostelForm(data=request.POST)
        price = Pricing_HostelForm(data=request.POST)
        formset = ImageFormset(request.POST or None, request.FILES or None)
        pid = request.session.get('property')
        Property_Uplo = Property_Upload.objects.get(id=pid)

        if hostel.is_valid() and price.is_valid() and formset.is_valid():

            for file in formset:
                if file.cleaned_data:
                    try:

                        photo = Gallery(pr=Property_Uplo, img=file.cleaned_data.get('img'))

                        photo.save()
                    except Exception as e:
                        break

            hostelinstance = hostel.save(commit=False)
            hostelinstance.pr = Property_Uplo
            priceinstance = price.save(commit=False)
            priceinstance.pr = Property_Uplo
            priceinstance.save()
            price.save()
            hostelinstance.price = priceinstance
            hostel_instance=hostel.save()
            for amenity in hostel_instance.amenities.all():
                hostel_instance.amenities.add(amenity)
                hostel_instance.save()

            return render(request,'hostupload/done.html')

    else:
        hostel = HostelForm()
        price = Pricing_HostelForm()
        ImageFormset = ImageFormset(queryset=Gallery.objects.none())

        return render(request,'hostupload/hostel.html',{'hostel':hostel,'price':price,'image':ImageFormset, })

def UploadHouseview(request):
    ImageFormset = modelformset_factory(Gallery, fields=('img',), extra=3 , max_num=8)

    if request.method=='POST':
        house = HouseForm(data=request.POST)
        price = Pricing_HouseForm(data=request.POST)
        formset = ImageFormset(request.POST or None, request.FILES or None)

        pid =  request.session.get('property')
        Property_Uplo = Property_Upload.objects.get(id=pid)

        if house.is_valid() and price.is_valid() and formset.is_valid():

            for file in formset:
                if file.cleaned_data:
                    try:

                        photo = Gallery(pr=Property_Uplo, img=file.cleaned_data.get('img'))

                        photo.save()
                    except Exception as e:
                        break


            houseinstance = house.save(commit=False)
            houseinstance.pr = Property_Uplo
            priceinstance = price.save(commit=False)
            priceinstance.pr = Property_Uplo
            priceinstance.save()
            price.save()
            houseinstance.price = priceinstance
            house_instance=house.save()
            for amenity in house_instance.amenities.all():
                house_instance.amenities.add(amenity)
                house_instance.save()

            return render(request,'hostupload/done.html')

    else:
        house = HouseForm()
        price = Pricing_HouseForm()
        ImageFormset = ImageFormset(queryset=Gallery.objects.none())

        return render(request,'hostupload/house.html',{'house':house,'price':price,'image':ImageFormset})


@login_required(login_url='login')
def UploadFormview(request):

    if request.method=='POST':
        upload = UploadForm(data=request.POST)
        address = AddressForm(data=request.POST)

        if upload.is_valid() and address.is_valid() :
            form = upload.save(commit=False)
            form.pr_type = upload.cleaned_data['pr_type']
            form.user = request.user
            add = address.save()
            form.address = add
            form.save()
            request.session['property'] = form.id
            if upload.cleaned_data['pr_type']=='1':
                return redirect('hostupload:hostel')
            else:
                return redirect('hostupload:house')

        else:
            print(upload.errors,address.errors)
    else:

        upload = UploadForm()
        address = AddressForm()

    return render(request,'hostupload/main-upload.html',{'upload':upload,'address':address})

niwas/hostupload/templates/hostupload/done.html
{% extends 'nav.html' %}
{% block content %}


<h1 class="jumbotron">You are Done!!!</h1>

{% endblock %}

niwas/hostupload/templates/hostupload/hostel.html
{% extends 'nav.html' %}
{% block content %}
    <form enctype="multipart/form-data" method="post">
      {% csrf_token %}

      {{ hostel.as_p }}
        <p>Pricing</p>
      {{ price.as_p }}
        {{ image.as_p }}
      <input type="submit" name="submit" value="register">
    </form>
{% endblock %}

niwas/hostupload/templates/hostupload/house.html
{% extends 'nav.html' %}
{% block content %}
    <form enctype="multipart/form-data" method="post">
      {% csrf_token %}
        <h2>Quantity</h2>
      {{ house.as_p }}
                <h2>Pricing</h2>

      {{ price.as_p }}
      {{ image.as_p }}
      <input type="submit" name="submit" value="register">
    </form>
{% endblock %}

niwas/hostupload/templates/hostupload/main-upload.html
{% extends 'nav.html' %}
{% block content %}
    <form enctype="multipart/form-data" method="post">
      {% csrf_token %}
      {{ upload.as_p }}
      {{ address.as_p }}
      <input type="submit" name="submit" value="register">
    </form>
{% endblock %}

niwas/hostupload/templates/hostupload/upload-main.html
{% extends 'nav.html' %}
{% block content %}
{% load widget_tweaks %}
  <div class="container">
  <div class="row">
    <p class="display-4" style="margin-left:5%;">Details</p>
  </div>


    <form class="text-center border border-light p-5" method="post">
        {% csrf_token %}
  <div class="row">
    <div class="col-md-8">
            <div class="card" style="height:auto; margin-left:5%;border-radius:20px;color:white;background-color:#0000007d;">
              <div class="card-body" style="margin-left:113px;padding-top:140px">
                <div class="row">
           <div class="col-lg-4">
            <div class="custom-control custom-checkbox ">
              {{ upload.shareable|add_class:"custom-control-input" }}
{#              <input type="checkbox" class="custom-control-input" id="defaultInline1">#}
              <label style="font-size:17px"  class="custom-control-label" for="shareable">Sharable</label>
            </div><br><br>
      </div>
      <div class="col-lg-4" style="padding-left: 100px;padding-right:0px;">
            <!-- Default inline 2-->
            <div class="custom-control custom-checkbox ">
                {{ upload.pr_is_personal|add_class:"custom-control-input" }}
{#              <input type="checkbox" class="custom-control-input" id="defaultInline2">#}
              <label style="font-size:17px"  class="custom-control-label" for="id_pr_is_personal">Personal Usage</label>
            </div><br>
      </div>
      </div>
            <!-- Default inline 3-->
            <div class="row">
              <div class="col-lg-4">
            <div class="custom-control custom-checkbox">
                {{ upload.for_business|add_class:"custom-control-input" }}

                {#<input type="checkbox" class="custom-control-input" id="defaultInline3" style="background-color:inherit;">#}
              <label style="font-size:17px" class="custom-control-label" for="id_for_business">Buisness purpose</label>
            </div><br>
      </div>

      <div class="col-lg-4" style="padding-left:100px;margin-top:-16px">
          {{ upload.pr_type|add_class:"mdb-select md-form" }}
{#            <select class="mdb-select md-form" style="color:white;background-color:#0000007d;border-radius:6px;width:150px;height:30px;">#}
{#              <option value="" disabled selected>Type</option>#}
{#              <option value="1">Hostel</option>#}
{#              <option value="2">Apartment</option>#}
{#              <option value="3">House</option>#}
{#          </select>#}

      <br><br>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-4">
          <div style="width:240px;" class="md-form">
                          <label for="id_street" style="color:white;">Street</label>

              {{ address.street|add_class:"form-control" }}

{#            <input type="text" id="form1" class="form-control" style="color:white;">#}
          </div>

        </div>
        <div class="col-lg-4" style="padding-left: 100px">
          <div style="width:240px;" class="md-form">
                          <label for="id_city" style="color:white;">City</label>

              {{ address.city|add_class:"form-control" }}

{#            <input type="text" id="form2" class="form-control" style="color:white;">#}
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-4">

              <div style="width:240px;" class="md-form">
                              <label for="id_state" style="color:white;">State</label>

                  {{ address.state|add_class:"form-control" }}

{#            <input type="text" id="form3" class="form-control" style="color:white;">#}
          </div>
        </div>
        <div class="col-lg-4" style="padding-left: 100px;">
          <div style="width:240px;" class="md-form">
                      <label for="id_zipcode" style="color:white;">Pincode</label>

              {{ address.zipcode|add_class:"form-control" }}

{#        <input type="text" id="form4" class="form-control" style="color:white;">#}
      </div>
        </div>

      </div>
      <br><br>
                    <button class="btn btn-info btn-block my-4" type="submit">submit</button>

      </div>

      </div>

    </div>
  </div>

    </form>
    <div class="col-md-4">
      <div class="card" style="border-radius:20px;color:white;background-color:#0000007d;">
        <div class="card-body">
          <span class="far fa-lightbulb" style="color:#00c5c5;font-size:larger;"></span> <span style="font-weight: 500;">Sharable:</span><br>
          <hr style="border-color:white;">
          Lorem estibulum dolor quis eleifend. Cras non ex ipsum.
           Ut pharetra scelerisque justo et tincidunt. Vivamus nisi enim, faucibus eu mattis id,
           aliqueAenean eu metus <br><br><br>
           <span class="far fa-lightbulb" style="color:#00c5c5;font-size:larger;"></span><span style="font-weight: 500;"> personal usage:</span><br>
           <hr style="border-color:white;">
           Lorem estibulum dolor quis eleifend. Cras non ex ipsum.
            Ut pharetra scelerisque justo et tincidunt. Vivamus nisi enim, faucibus eu mattis id,
            aliqueAenean eu metus <br><br><br>
            <span class="far fa-lightbulb" style="color:#00c5c5;font-size:larger;"></span><span style="font-weight: 500;"> Business purpose:</span><br>
            <hr style="border-color:white;">
            Lorem estibulum dolor quis eleifend. Cras non ex ipsum.
             Ut pharetra scelerisque justo et tincidunt. Vivamus nisi enim, faucibus eu mattis id,
             aliqueAenean eu metus <br>
        </div>
      </div>
    </div>

  </div>
<script type="text/javascript" src="js/popper.min.js"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="js/bootstrap.min.js"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="js/mdb.min.js"></script>
<script type="text/javascript">

{% endblock %}