niwas/client_page1/urls.py
from django.urls import path
from . import views
app_name="client_page1"
urlpatterns = [
    path('home/', views.home,name='client_page1-home'),
    path('block/', views.block,name='client_page1-block'),
    path('maps/', views.map,name='client_page1-maps'),
]

niwas/client_pages2/urls.py
from django.urls import re_path, include, path
from . import views
app_name="client_pages2"
urlpatterns = [
    path('home/<int:id>' , views.home , name='home'),
    path('feedback/<int:id>' , views.feedback , name='feedback'),
]

niwas/niwas/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path,include,re_path

from account.views import user_login,index
from client.views import  home
from niwas import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='index'),
    path('login/', user_login, name='login'),
    path('hosting/' , include('hostupload.urls')),
    path('account/', include("account.urls")),
    re_path(r'^accounts/', include('account.passwords.urls')),
    path('client_page1/' , include('client_page1.urls')),
    path('client_pages2/',include('client_pages2.urls')),
    path('client/',include('client.urls')),

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

niwas/client_page1/models.py
from django.db import models

# Create your models here.
class variables(models.Model):
    selected = models.CharField(max_length=200)

from django.contrib.auth.models import User


niwas/client_page1/forms.py
from django.forms import ModelForm
from .models import MyModel

class MyModelForm(ModelForm):
    class Meta:
        model = MyModel
        fields = ['color']

niwas/client_page1/views.py
from django.shortcuts import render
from django.http import HttpResponse
from hostupload.models import *


def map(request):
    p=[]
    print(k)
    for i in k:
        x = k
        print(x)
        s=','
        address=[]
        address.append(i.address.street)
        address.append(i.address.city)
        address.append(i.address.state)
        addres=s.join(address)
        p.append(addres)
    print(p)
    sel={
    "selected":p
    }
    return render(request,'client_page1/maps.html',context=sel)

def priceh(h,home):
    if h==1:
        price=home.price.single_a+home.price.single_wa+home.price.double_a+home.price.double_wa+home.price.triple_a+home.price.triple_wa+home.price.floorbed+home.price.cleaning+home.price.security+home.price.extra
    if h==2:
        price=home.price.single_a+home.price.single_wa+home.price.double_a+home.price.double_wa+home.price.triple_a+home.price.triple_wa+home.price.four_a+home.price.four_wa+home.price.cab+home.price.food+home.price.cleaning+home.price.security+home.price.extra
    print(price)
    return price


def block(request):
    gallery = []
    avgrating = []
    l = []
    house = House.objects.all()
    hostel = Hostel.objects.all()
    for housei in house:
        rating = House.objects.get(pr=housei.pr)
        avgrating.append(rating.avg_rating)
        l.append(housei.pr)
    for hosteli in hostel:
        rating = Hostel.objects.get(pr=hosteli.pr)
        avgrating.append(rating.avg_rating)
        l.append(hosteli.pr)
    print(l)
    for home in l:
        slide = Gallery.objects.filter(pr=home)
        print(slide)
        gallery.append(slide[0].img)
    global k
    k = l
    mylist = zip(l, gallery, avgrating)
    sel = {"selected": mylist}
    return render(request, 'client_page1/block.html', context=sel)

def home(request):
    global k
    place=request.session['place']
    checkin=request.session['checkin']
    checkout = request.session['checkout']
    guest=request.session['guests']
    print(guest)
    if place:
        addressh=Address.objects.filter(city = place)
        house =[]
        hostel=[]
        gallery=[]
        l=[]
        avgrating=[]
        print(addressh)
        for address in addressh:
            houses=House.objects.filter(pr=Property_Upload.objects.get(address=address))
            if houses:
                house.append(houses[0])
            hostels=Hostel.objects.filter(pr=Property_Upload.objects.get(address=address))
            if hostels:
                hostel.append(hostels[0])
    else:
        hostel = Hostel.objects.all()
        house=House.objects.all()
    if request.method=="POST":
        low=500
        medium=1000
        high=15000
        housetype = request.POST.get('housetype')
        pricerange = request.POST.get('pricerange')
        checkinf=request.POST.get("checkin")
        checkoutf=request.POST.get("checkout")
        checkin=checkinf
        checkout=checkoutf
        request.session['checkin'] = checkin
        request.session['checkout'] = checkout
        if pricerange != "none":
            phouse = []
            phostel = []
            for house in house:
                price = priceh(1, house)
                print(price)
                if pricerange == "low" and 0 < price < 5000:
                    phouse.append(house)
                if pricerange == "meadium" and 5000 < price < 10000:
                    phouse.append(house)
                if pricerange == "high" and 10000 < price:
                    phouse.append(house)
            for hostel in hostel:
                price = priceh(2, hostel)
                if pricerange == "low" and 0 < price < 5000:
                    phouse.append(hostel)
                if pricerange == "meadium" and 5000 < price < 10000:
                    phouse.append(hostel)
                if pricerange == "high" and 10000 < price:
                    phouse.append(hostel)
            house = phouse
            hostel = phostel
            print(house)
            print(hostel)
        if housetype!="none" :
            if housetype=="house":
                for housei in house:
                    nsingle,nsinglew,ndouble,ndoublew,ntriple,ntriplew=fil(housei,checkin,checkout,guest)
                    total=nsingle+nsinglew+2*ndouble+2*ndoublew+3*ntriple+3*ntriplew
                    print(total)
                    if total >= guest:
                        l.append(housei.pr)
                k=l
                print(checkin)
                print(checkout)
                for i in l:
                    slide=Gallery.objects.get(id=i.id)
                    gallery.append(slide.img)
                    rating=House.objects.get(pr=i)
                    avgrating.append(rating.avg_rating)
                print(gallery)
                mylist = zip(l , gallery,avgrating)
                sel={"selected" : mylist,"checkin":checkin,"checkout":checkout}
                return render(request,'client_page1/home.html',context=sel)
            if housetype=="hostel":
                for hosteli in hostel:
                    nsingle,nsinglew,ndouble,ndoublew,ntriple,ntriplew=fil1(hosteli,checkin,checkout,guest)
                    total=nsingle+nsinglew+2*ndouble+2*ndoublew+3*ntriple+3*ntriplew
                    print(total)
                    if total >= guest:
                        l.append(hosteli.pr)
                k=l
                print(checkin)
                print(checkout)
                for i in l:
                    slide=Gallery.objects.get(id=i.id)
                    gallery.append(slide.img)
                    rating=Hostel.objects.get(pr=i)
                    avgrating.append(rating.avg_rating)
                print(gallery)
                mylist = zip(l , gallery,avgrating)
                sel={"selected" : mylist,"checkin":checkin,"checkout":checkout}
                return render(request,'client_page1/home.html',context=sel)
    # housel=fil(house,checkin,checkout,guest)
    for housei in house:
        nsingle,nsinglew,ndouble,ndoublew,ntriple,ntriplew=fil(housei,checkin,checkout,guest)
        total=nsingle+nsinglew+2*ndouble+2*ndoublew+3*ntriple+3*ntriplew
        print(total)
        if total >= guest:
            l.append(housei.pr)
            avgrating.append(housei.avg_rating)
    for hosteli in hostel:
        nsingle,nsinglew,ndouble,ndoublew,ntriple,ntriplew=fil1(hosteli,checkin,checkout,guest)
        total=nsingle+nsinglew+2*ndouble+2*ndoublew+3*ntriple+3*ntriplew
        print(total)
        if total >= guest:
            l.append(hosteli.pr)
            avgrating.append(hosteli.avg_rating)
    k=l
    print(checkin)
    print(checkout)
    print(l)
    for i in l:
        print(i.id)
        slide=Gallery.objects.get(id=i.id)
        gallery.append(slide.img)
    print(gallery)
    mylist = zip(l,gallery,avgrating)
    sel={"selected": mylist,"checkin":checkin,"checkout":checkout}
    return render(request,'client_page1/home.html',context=sel)

def fil(house,checkin,checkout,guest):
    # a=int(checkin[0:4])
    # a1=int(checkin[5:7])
    # a2=int(checkin[8:10])
    # b=int(checkout[0:4])
    # b1=int(checkout[5:7])
    # b2=int(checkout[8:10])
    bhouse=Booking_House.objects.filter(pr = house.pr)
    single=house.single_a
    singlew=house.single_wa
    double=house.double_a
    doublew=house.double_wa
    triple=house.triple_a
    triplew=house.triple_wa
    bsingle=0
    bsinglew=0
    bdouble=0
    bdoublew=0
    btriple=0
    btriplew=0
    if len(bhouse) != 0:
        for bhouse in bhouse:
            bcheckind=bhouse.check_in
            bcheckoutd=bhouse.check_out
            bcheckin = bcheckind.isoformat()
            bcheckout = bcheckoutd.isoformat()
            c=int(bcheckin[0:4])
            c1=int(bcheckin[5:7])
            c2=int(bcheckin[8:10])
            d=int(bcheckout[0:4])
            d1=int(bcheckout[5:7])
            d2=int(bcheckout[8:10])
            if checkin<bcheckin and checkout<bcheckout:
            # if a2<c2 and a1<=c1 and a<=c:
            #     if b2<d2 and b1<=d1 and b<=d:
                bsingle+=bhouse.single_a
                bsinglew+=bhouse.single_wa
                bdouble+=bhouse.double_a
                bdoublew+=bhouse.double_wa
                btriple+=bhouse.triple_a
                btriplew+=bhouse.triple_wa
            if checkin>bcheckin and checkout<bcheckout:
            # if a2>c2 and a1>=c1 and a>=c:
            #     if b2<d2 and b1<=d1 and b<=d:
                bsingle+=bhouse.single_a
                bsinglew+=bhouse.single_wa
                bdouble+=bhouse.double_a
                bdoublew+=bhouse.double_wa
                btriple+=bhouse.triple_a
                btriplew+=bhouse.triple_wa
            if checkin>bcheckin and checkout>bcheckout:
            # if a2>c2 and a1>=c1 and a>=c:
            #     if b2>d2 and b1>=d1 and b>=d:
                bsingle+=bhouse.single_a
                bsinglew+=bhouse.single_wa
                bdouble+=bhouse.double_a
                bdoublew+=bhouse.double_wa
                btriple+=bhouse.triple_a
                btriplew+=bhouse.triple_wa
            if checkin==bcheckin and checkout==bcheckout:
            # if a2<=c2 and a1<=c1 and a<=c:
            #     if b2<=d2 and b1<=d1 and b<=d:
                bsingle=bsingle+bhouse.single_a
                bsinglew+=bhouse.single_wa
                bdouble+=bhouse.double_a
                bdoublew+=bhouse.double_wa
                btriple+=bhouse.triple_a
                btriplew+=bhouse.triple_wa
    nsingle=single-bsingle
    nsinglew=singlew-bsinglew
    ndouble=double-bdouble
    ndoublew=doublew-bdoublew
    ntriple=triple-btriple
    ntriplew=triplew-btriplew

niwas/templates/client_page1/block.html
{% extends 'nav.html' %}


  {% block content %}
  <div class="container-fluid">
        {% if selected %}
          {% for each,img,avg_rating in selected %}
          <a href="{% url 'client_pages2:home' id=each.id %}">
              <div class="card" style="float:left">
                <img class="card-img-top" src="{{img.url}}" style="width:100%;height:190px;">
                <div class="card-text">
                  {{avg_rating}}
                    <p>{% with ''|center:avg_rating as range %}
                        {% for i in range %}
                            <span class="fa fa-star checked"></span>
                        {% endfor %}
                    {% endwith %}

  </p>
                </div>
              </div>
            </a>
        {% endfor %}
        {% endif %}
</div>
    {% endblock %}

niwas/templates/client_page1/home.html
{% extends 'nav.html' %}
{% load staticfiles %}

  {% block content %}
  <link rel="stylesheet" type="text/css" href="{% static 'client_page1/style.css' %}">
<div class="transparent" class="container-fluid">
  <div class="place">
    <div class="center">
			<div class="row">
				<div class="col">
          <div style="color:black;">
					<form action="{% url 'client_page1:client_page1-home' %}" method="POST" name = "trial">
            {%  csrf_token %}
            <input type="date" name="checkin" value="{{checkin}}">
            <input type="date" name="checkout" value="{{checkout}}">
						<select  name="housetype" id='name'>
							<option disabled selected value="house type">house type</option>
							<option value="houses">houses</option>
							<option value="hostel">hostel</option>
						</select>
            <select  name="pricerange">
							<option disabled selected value="price range">price range</option>
							<option value="low">low</option>
							<option value="medium">medium</option>
              <option value="high">high</option>
						</select>
					  <button type="submit">search</button>
					</form>
        </div>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-4">
      <iframe id ="myIframe" src="{% url 'client_page1:client_page1-maps' %}" width="100%" height="650px"></iframe>
    </div>
    <div class="col-sm-8">
      {% if selected %}
        {% for each,img,avg_rating in selected %}
        <a href="{% url 'client_pages2:home' id=each.id %}">
            <div class="card" style="float:left">
              <img class="card-img-top" src="{{img.url}}" style="width:100%;height:190px;">
              <div class="card-text">
                {{avg_rating}}
                  <p>{% with ''|center:avg_rating as range %}
                      {% for i in range %}
                          <span class="fa fa-star checked"></span>
                      {% endfor %}
                  {% endwith %}

</p>
              </div>
            </div>
          </a>
      {% endfor %}
      {% endif %}

  </div>
</div>
  {% endblock %}

niwas/templates/client_page1/maps.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBGBa0ZLrpyDs9IZ1Y4gk0_hppyt6k1Kr4&callback=myMap"></script>
  <title>My Google Map</title>
  <style>
    #map{
      height:650px;
      width:100%;
    }
  </style>
</head>
<body>
 <div id="map"></div>
 <script> var locations=[]</script>
 {% for each in selected%}
 <script> locations.push('{{each}}')
 </script>
 {% endfor%}
      <script type="text/javascript">
      console.log(locations)
  var delay = 100;
  var infowindow = new google.maps.InfoWindow();
  var latlng = new google.maps.LatLng(17.3850, 78.4867);
  var mapOptions = {
    zoom: 15,
    center: latlng,
    mapTypeId: google.maps.MapTypeId.ROADMAP
  }
  var geocoder = new google.maps.Geocoder();
  var map = new google.maps.Map(document.getElementById("map"), mapOptions);
  var bounds = new google.maps.LatLngBounds();

  function geocodeAddress(address, next) {
    geocoder.geocode({address:address}, function (results,status)
      {
         if (status == google.maps.GeocoderStatus.OK) {
          var p = results[0].geometry.location;
          var lat=p.lat();
          var lng=p.lng();
          createMarker(address,lat,lng);
        }
        else {
           if (status == google.maps.GeocoderStatus.OVER_QUERY_LIMIT) {
            nextAddress--;
            delay++;
          } else {
                        }
        }
        next();
      }
    );
  }
 function createMarker(add,lat,lng) {
   var contentString = add;
   var marker = new google.maps.Marker({
     position: new google.maps.LatLng(lat,lng),
     map: map,
           });

  google.maps.event.addListener(marker, 'click', function() {
     infowindow.setContent(contentString);
     infowindow.open(map,marker);
   });

   bounds.extend(marker.position);

 }
 // console.log(locations)
//   var locations = [
//             //'Hydernagar,hyderabad, India',
//            //'Kompally,hyderabad, India',
//            'Bangaluru, Karnataka, India',
//            //'kukatpally,hyderabad India',
//            //'Gurgaon, Haryana, India',
//            //'Cannaught Place, New Delhi, India',
//            //'Bandra, Mumbai, India',
//            //'Nainital, Uttranchal, India',
//            //'Guwahati, India',
//            //'West Bengal, India',
//            //'Jammu, India',
//            //'Kanyakumari, India',
//            //'Kerala, India',
//            //'Himachal Pradesh, India',
//            //'Shillong, India',
//            //'Chandigarh, India',
//            //'Dwarka, New Delhi, India',
//            //'Pune, India',
//            //'Indore, India',
//            //'Orissa, India',
//            //'Shimla, India',
//            //'Gujarat, India'
//   ];
console.log(locations[0])
  var nextAddress = 0;
  function theNext() {
    if (nextAddress < locations.length) {
      setTimeout('geocodeAddress("'+locations[nextAddress]+'",theNext)', delay);
      nextAddress++;
    } else {
      map.fitBounds(bounds);
    }
  }
 theNext();
</script>

</body>
</html>