niwas/client/urls.py
from django.conf.urls import url
from django.contrib import admin
from .import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth.views import LoginView
from django.conf import settings
from django.conf.urls.static import static


app_name = 'client'

urlpatterns = [

        url(r'^bookRoom/(?P<id>[0-9]+)$', views.bookRoom, name='bookRoom'),
        url(r'^bookHostel/(?P<id>[0-9]+)$', views.bookHostel , name='bookHostel'),
        url(r'^booking_house/(?P<id>[0-9]+)$', views.store_data_house, name='booking_house'),
        url(r'^booking_hostel/(?P<id>[0-9]+)$', views.store_data_hostel, name='booking_hostel'),
        url(r'^cancel_booking_house/(?P<id>[0-9]+)$', views.cancelbooking_house, name='house_cancelbooking'),
        url(r'^cancel_booking_hostel/(?P<id>[0-9]+)$', views.cancelbooking_hostel, name='hostel_cancelbooking'),
        url(r'^viewbookings/$', views.mybookings , name='viewbookings'),

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

niwas/niwas/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path,include,re_path

from account.views import user_login,index
from client.views import  home
from niwas import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='index'),
    path('login/', user_login, name='login'),
    path('hosting/' , include('hostupload.urls')),
    path('account/', include("account.urls")),
    re_path(r'^accounts/', include('account.passwords.urls')),
    path('client_page1/' , include('client_page1.urls')),
    path('client_pages2/',include('client_pages2.urls')),
    path('client/',include('client.urls')),

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

niwas/client/models.py
from django.db import models

# Create your models here.

niwas/client/forms.py
from django import forms
from django.forms import ModelForm

from hostupload.models import *


class DetailForm(forms.Form):
    place = forms.CharField(max_length=100)
    checkin = forms.DateField()

    checkout = forms.DateField()
    guests = forms.IntegerField()





class booking_form(ModelForm):
    class Meta:
        model = Booking_House
        fields = '__all__'



class booking_form(ModelForm):
    class Meta:
        model = Booking_Hostel
        fields = '__all__'

niwas/client/views.py
import datetime
import operator

from django.core.mail import EmailMessage

from django.contrib.auth.decorators import login_required
from django.contrib.sites.shortcuts import get_current_site
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.urls import reverse
from django.utils.http import urlsafe_base64_encode

from hostupload import models
from client.forms import DetailForm, booking_form
# Create your views here.
from hostupload.models import *



def home(request):

    if request.method == "POST":
        form = DetailForm(request.POST)
        if form.is_valid():
            place = form.cleaned_data['place']
            request.session['place'] = place
            checkin = str(form.cleaned_data['checkin'])
            request.session['checkin'] = checkin

            checkout = str(form.cleaned_data['checkout'])
            request.session['checkout'] = checkout

            guests = form.cleaned_data['guests']
            request.session['guests'] = guests
            return redirect('/client_page1/home/')

    else:
        form = DetailForm()

    dictionary = {}
    for houses in House.objects.all():
        if houses.avg_rating >= 1:
            dictionary[houses.pr_id] = houses.avg_rating

    sorted_d = sorted(dictionary.items(), key=operator.itemgetter(1), reverse=True)
    key= [x[0] for x in sorted_d]
    keys = key[0:8]
    image_list = []
    address_list = []
    rating_list = []
    for i in keys:
        img = Gallery.objects.filter(pr_id=i)
        image = img[0].img
        image_list.append(image)
        address = Address.objects.get(id=i)
        street = address.street
        city = address.city
        state = address.state

        add = street + ' , ' + city + ' , ' + state
        address_list.append(add)
        rating = dictionary[i]
        rating_list.append(rating)
    mylist = zip(keys,image_list,address_list,rating_list)


    context = {'form':form, 'mylist':mylist}
    return render(request, 'client/home.html', context)








@login_required(login_url='project:login')
def bookRoom(request,id):

    FirstDate = request.session['checkin']
    SecDate =  request.session['checkout']
    guests = request.session['guests']
    Checkin = datetime.datetime.strptime(FirstDate, "%Y-%m-%d").date()
    Checkout = datetime.datetime.strptime(SecDate, "%Y-%m-%d").date()
    timedeltaSum = Checkout - Checkin

    StayDuration = timedeltaSum.days

    # request.session['single_a'] = 5
    # request.session['single_wa'] = 5
    # request.session['double_a'] = 5
    # request.session['double_wa'] = 5
    # request.session['triple_a'] = 5
    # request.session['triple_wa'] = 5
    # request.session['floorbed'] = 5

    property_id=id


    pricing = Pricing_House.objects.get(pr=property_id)

    cost_house = (request.session['single_a']) * (pricing.single_a) + (request.session['single_wa']) * (
        pricing.single_wa) + (request.session['double_a']) * (pricing.double_a) + (request.session['double_wa']) * (
                     pricing.double_wa) + (request.session['triple_a']) * (pricing.triple_a) + (
                 request.session['triple_wa']) * (pricing.triple_wa) + pricing.cleaning + pricing.security + pricing.extra

    total_cost = cost_house * StayDuration



    property = Property_Upload.objects.get(id=property_id)
    street = property.address.street
    city = property.address.city
    state= property.address.state
    zipcode = property.address.zipcode

    id = id


    context = {'checkin': FirstDate, 'checkout':SecDate,'stayduration':StayDuration,'id':id,'totalcost':total_cost, 'street':street,'city':city,'state':state,'zipcode':zipcode,'guests':guests}
    return render(request, 'project/booking_house.html', context)



def store_data_house(request,id):
    FirstDate = request.session['checkin']
    SecDate = request.session['checkout']

    Checkin = datetime.datetime.strptime(FirstDate, "%Y-%m-%d").date()
    Checkout = datetime.datetime.strptime(SecDate, "%Y-%m-%d").date()
    timedeltaSum = Checkout - Checkin
    StayDuration = timedeltaSum.days

    # request.session['single_a'] = 5
    # request.session['single_wa'] = 5
    # request.session['double_a'] = 5
    # request.session['double_wa'] = 5
    # request.session['triple_a'] = 5
    # request.session['triple_wa'] = 5
    # request.session['floorbed'] = 5


    pricing = Pricing_House.objects.get(pr=id)
    pr_ins = Property_Upload.objects.get(id=id)

    user = request.user

    cost_house= (request.session['single_a'])*(pricing.single_a) + (request.session['single_wa'])*(pricing.single_wa) +(request.session['double_a'])*(pricing.double_a) +(request.session['double_wa'])*(pricing.double_wa)+ (request.session['triple_a'])*(pricing.triple_a) + (request.session['triple_wa'])*(pricing.triple_wa)  + pricing.cleaning + pricing.security + pricing.extra

    total_cost = cost_house* StayDuration



    p=Booking_House.objects.create( check_in=FirstDate, check_out=SecDate, price_paid=total_cost,single_a = request.session['single_a'], single_wa= request.session['single_wa'], double_a=request.session['double_a'], double_wa=request.session['double_wa'], triple_a=request.session['triple_a'], triple_wa=request.session['triple_wa'],pr=pr_ins,user=user)
    p.save()

    del request.session['checkin']
    del request.session['checkout']
    del request.session['single_a']
    del request.session['single_wa']
    del request.session['double_a']
    del request.session['double_wa']
    del request.session['triple_a']
    del request.session['triple_wa']








    current_site = get_current_site(request)
    mail_subject = 'Your Booking is confirmed.'
    message = render_to_string('client/booking_confirm.html', {
        'user': user,
        'domain': current_site.domain,
        'id': id,
    })
    to_email = request.user.email
    email = EmailMessage(
        mail_subject, message, to=[to_email]
    )
    email.send()






    context = { 'user_name': user}

    return render(request, 'project/payment.html', context)



@login_required(login_url='project:login')
def bookHostel(request,id):
    FirstDate = request.session['checkin']
    SecDate = request.session['checkout']
    Checkin = datetime.datetime.strptime(FirstDate, "%Y-%m-%d").date()
    Checkout = datetime.datetime.strptime(SecDate, "%Y-%m-%d").date()
    timedeltaSum = Checkout - Checkin
    StayDuration = timedeltaSum.days

    # request.session['single_a'] = 5
    # request.session['single_wa'] = 5
    # request.session['double_a'] = 5
    # request.session['double_wa'] = 5
    # request.session['triple_a'] = 5
    # request.session['triple_wa'] = 5

    property_id = id
    pricing = Pricing_Hostel.objects.get(id=property_id)
    guests = request.session['guests']
    cost_hostel = (request.session['single_a'])*(pricing.single_a) + (request.session['single_wa'])*(pricing.single_wa) +(request.session['double_a'])*(pricing.double_a) +(request.session['double_wa'])*(pricing.double_wa)+ (request.session['triple_a'])*(pricing.triple_a) + (request.session['triple_wa'])*(pricing.triple_wa) + pricing.cleaning + pricing.security + pricing.extra + pricing.cab + pricing.food

    total_cost = cost_hostel * StayDuration


    id = id

    property = Property_Upload.objects.get(id=property_id)
    street = property.address.street
    city = property.address.city
    state= property.address.state
    zipcode = property.address.zipcode

    images = Gallery.objects.get(pr=property_id)
    image = images.img


    context = {'checkin': FirstDate, 'checkout':SecDate,'stayduration':StayDuration, 'image':image, 'totalcost':total_cost, 'street':street,'city':city,'state':state,'zipcode':zipcode,'guests':guests,'id':id}

    return render(request, 'project/booking_hostel.html', context)





def store_data_hostel(request,id):
    FirstDate = request.session['checkin']
    SecDate = request.session['checkout']

    Checkin = datetime.datetime.strptime(FirstDate, "%Y-%m-%d").date()
    Checkout = datetime.datetime.strptime(SecDate, "%Y-%m-%d").date()
    timedeltaSum = Checkout - Checkin
    StayDuration = timedeltaSum.days

    # request.session['single_a'] = 5
    # request.session['single_wa'] = 5
    # request.session['double_a'] = 5
    # request.session['double_wa'] = 5
    # request.session['triple_a'] = 5
    # request.session['triple_wa'] = 5

    user = request.user
    pricing = Pricing_Hostel.objects.get(id=id)
    pr_ins = Property_Upload.objects.get(id=id)
    cost_hostel = (request.session['single_a'])*(pricing.single_a) + (request.session['single_wa'])*(pricing.single_wa) +(request.session['double_a'])*(pricing.double_a) +(request.session['double_wa'])*(pricing.double_wa)+ (request.session['triple_a'])*(pricing.triple_a) + (request.session['triple_wa'])*(pricing.triple_wa) + pricing.cleaning + pricing.security + pricing.extra + pricing.cab + pricing.food

    total_cost = cost_hostel * StayDuration

    p = Booking_Hostel.objects.create(check_in=FirstDate, check_out=SecDate, price_paid=total_cost, single_a = request.session['single_a'], single_wa=request.session['single_wa'], double_a=request.session['double_a'], double_wa=request.session['double_wa'], triple_a=request.session['triple_a'], triple_wa=request.session['triple_wa'],pr=pr_ins,user=user)
    p.save()


    current_site = get_current_site(request)
    mail_subject = 'Your Booking is confirmed.'
    message = render_to_string('client/booking_confirm.html', {
        'user': user,
        'domain': current_site.domain,
        'id': id,
    })
    to_email = request.user.email
    email = EmailMessage(
        mail_subject, message, to=[to_email]
    )
    email.send()















    del request.session['checkin']
    del request.session['checkout']
    del request.session['single_a']
    del request.session['single_wa']
    del request.session['double_a']
    del request.session['double_wa']
    del request.session['triple_a']

niwas/client/templates/project/booking_form.html
{% extends 'base.html' %}

{% block body %}
<form method="post" action="">
    {% csrf_token %}
    <table border="1">
    {{ form.as_p}}
    <input type="submit" value="submit">
    </table>
</form>
{% endblock %}


niwas/client/templates/project/booking_hostel.html
{% extends 'nav.html' %}
{% load staticfiles %}
{% block content %}

    <link rel="stylesheet" type="text/css" href="{% static 'project/style.css' %}"/>

      <!-- //title -->
      <!-- content -->

      <div class="porduct-order-agile"  style="background-image: url('{% static 'project/images/b1.jpg' %}')">
          <center><h1 style="font-size: x-large">Confirm your booking</h1></center>
         <form action="{% url 'client:booking_hostel' id %}" method="post">
             {% csrf_token %}
            <div class="form-group">
               <p>Name</p>
               <input type="text" name="name" placeholder="Alice Willson" required="" value="{{ user }}">
            </div>
            <div class="form-group">
               <p>Email </p>
               <input type="email" placeholder="example@mail.com" required="" value="{{ user.email }}">
            </div>

            <div class="main">

               <div class="form-left-to-w3l">
                  <p>Street Address</p>
                  <input type="text" name="address" placeholder="" required="" value="{{ street }}">
               </div>
            </div>
            <div class="main">
               <div class="form-left-to-w3l">
                  <p>City</p>
                  <input type="text" name="city" placeholder="" required="" value="{{ city }}" >
                  <div class="clear"></div>
               </div>
               <div class="form-left-to-w3l">
                  <p>State</p>
                  <input type="text" name="state" placeholder="" required="" value="{{ state }}">
                  <div class="clear"></div>
               </div>
            </div>
            <div class="main">
               <div class="form-left-to-w3l">
                  <p>Pin Code</p>
                  <input type="text" name="Pin code" placeholder="Pin Code" required="" value="{{ zipcode }}">
                  <div class="clear"></div>
               </div>
                <div class="form-left-to-w3l">
                  <p>Checkin</p>
                  <input type="text" name="Checkin" placeholder="Pin Code" required="" value="{{ checkin }}">
                  <div class="clear"></div>
               </div>
                <div class="form-left-to-w3l">
                  <p>Checkout</p>
                  <input type="text" name="Pin code" placeholder="Pin Code" required="" value="{{ checkout }}">
                  <div class="clear"></div>
               </div>
                <div class="form-left-to-w3l">
                  <p>Total INR</p>
                  <input type="text" name="Pin code" placeholder="Pin Code" required="" value="{{ totalcost }}">
                  <div class="clear"></div>
               </div>

            </div>


            <button type="submit" class="btn btn-primary">Confirm</button>
         </form>
      </div>

{% endblock %}


niwas/client/templates/project/booking_house.html
{% extends 'nav.html' %}
{% load staticfiles %}
{% load static %}
{% block content %}

    <link rel="stylesheet" type="text/css" href="{% static 'project/style.css' %}"/>

      <!-- //title -->
      <!-- content -->

      <div class="porduct-order-agile" style="background-image: url('{% static 'project/images/b1.jpg' %}')">
          <center><h1 style="font-size: x-large">Confirm your booking</h1></center>
         <form action="{% url 'client:booking_house' id %}" method="post">
             {% csrf_token %}
            <div class="form-group">
               <p>Name</p>
               <input type="text" name="name" placeholder="Alice Willson" required="" value="{{ user }}">
            </div>
            <div class="form-group">
               <p>Email </p>
               <input type="email" placeholder="example@mail.com" required="" value="{{ user.email }}">
            </div>

            <div class="main">

               <div class="form-left-to-w3l">
                  <p>Street Address</p>
                  <input type="text" name="address" placeholder="" required="" value="{{ street }}">
               </div>
            </div>
            <div class="main">
               <div class="form-left-to-w3l">
                  <p>City</p>
                  <input type="text" name="city" placeholder="" required="" value="{{ city }}">
                  <div class="clear"></div>
               </div>
               <div class="form-left-to-w3l">
                  <p>State</p>
                  <input type="text" name="state" placeholder="" required="" value="{{ state }}">
                  <div class="clear"></div>
               </div>
            </div>
            <div class="main">
               <div class="form-left-to-w3l">
                  <p>Pin Code</p>
                  <input type="text" name="Pin code" placeholder="Pin Code" required="" value="{{ zipcode }}">
                  <div class="clear"></div>
               </div>
                <div class="form-left-to-w3l">
                  <p>Checkin</p>
                  <input type="text" name="Checkin" placeholder="Pin Code" required="" value="{{ checkin }}">
                  <div class="clear"></div>
               </div>
                <div class="form-left-to-w3l">
                  <p>Checkout</p>
                  <input type="text" name="Pin code" placeholder="Pin Code" required="" value="{{ checkout }}">
                  <div class="clear"></div>
               </div>
                <div class="form-left-to-w3l">
                  <p>Total INR</p>
                  <input type="text" name="Pin code" placeholder="Pin Code" required="" value="{{ totalcost }}">
                  <div class="clear"></div>
               </div>

            </div>


            <button type="submit" class="btn btn-primary">Confirm</button>
         </form>
      </div>

{% endblock %}


niwas/client/templates/project/detail_form.html
{% extends 'base.html' %}

{% block body %}
<form method="post" action="">
    {% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-default" type="submit" value="Submit" />

</form>
{% endblock %}


niwas/client/templates/project/login.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <h1>Welcome</h1>
    <p>
        You can log in here!
    </p>
    <h2>Login</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next }}">
        {% endif %}
        <button type="submit">Login</button>
    </form>
</div>
{% endblock %}


niwas/client/templates/project/logout.html



<div class="container">
    <h1>Logged out</h1>
    <p>
        You have logged out!
    </p>
</div>


niwas/client/templates/project/mybookings.html
{% extends 'nav.html' %}

{% block content %}
<a class="btn btn-default pull-right" href="{% url 'index' %}">Back</a>
<div class="row">
  <div class="col-md-6 col-md-offset-3 ">



      <h4>My Bookings:</h4>

      <br>



      {% for booking in bookings %}
        <a class="btn btn-sm btn-danger pull-right" href="{% url 'client:house_cancelbooking' booking.id %}">Cancel</a>
        <p><u>Booking id:{{booking.id}}</u></p>

        <p><mark>Check-in Date :</mark> {{booking.check_in}}.  </p>
        <p><mark>Check-out Date:</mark> {{booking.check_out}}.  </p>
        <p><mark>Total Price :</mark> ₹{{booking.price_paid}}.  </p>

         <br>
      {%endfor%}
      {% for booking in hostel_bookings %}
          <a class="btn btn-sm btn-danger pull-right" href="{% url 'client:hostel_cancelbooking' booking.id %}">Cancel</a>
        <p><u>Booking id:{{booking.id}}</u></p>

        <p><mark>Check-in Date :</mark> {{booking.check_in}}.  </p>
        <p><mark>Check-out Date:</mark> {{booking.check_out}}.  </p>
        <p><mark>Total Price :</mark> ₹{{booking.price_paid}}.  </p>

         <br>

      {% endfor %}

    </div>
  </div>

{% endblock %}


niwas/client/templates/project/payment.html
{% extends 'nav.html' %}

{% block content %}
<center>
    <div class="jumbotron">
   <h2>Hello, {{ user }}</h2> <br>
    Your booking has been confirmed.<br>
    Please Check your mail box for details and feedback.
    <br><br><br>
    </div>
</center>


{% endblock %}